ARG GO_VERSION=1.25
FROM golang:${GO_VERSION}-alpine AS cpm-builder
RUN apk add --no-cache git
RUN git clone --depth 1 https://github.com/CognitiveOS-Project/cpm.git /cpm
WORKDIR /cpm
RUN CGO_ENABLED=0 go build -ldflags="-s -w" -o /usr/local/bin/cpm ./cmd/cpm

FROM golang:${GO_VERSION}-alpine

ARG WORKDIR=.
WORKDIR /src
COPY ${WORKDIR} .

RUN apk add --no-cache jq
COPY --from=cpm-builder /usr/local/bin/cpm /usr/local/bin/cpm
RUN mkdir -p /out

RUN cpm pack
RUN cpm info cognitive.json --json > /out/pkg.json
RUN cp *.cgp /out/

FROM alpine
COPY --from=1 /out /out
